export const colors = {
  white: '#fff',
  gray: {
    50: 'var(--blockstudio-editor-50)',
    100: 'var(--blockstudio-editor-100)',
    200: 'var(--blockstudio-editor-200)',
    300: 'var(--blockstudio-editor-300)',
    400: 'var(--blockstudio-editor-400)',
    500: 'var(--blockstudio-editor-500)',
    600: 'var(--blockstudio-editor-600)',
    700: 'var(--blockstudio-editor-700)',
    800: 'var(--blockstudio-editor-800)',
    900: 'var(--blockstudio-editor-900)',
  },
  primary: 'var(--wp-admin-theme-color)',
  highlight: 'var(--blockstudio-editor-highlight)',
  changed: 'var(--blockstudio-editor-changed)',
  error: 'var(--blockstudio-editor-error)',
  success: 'var(--blockstudio-editor-success)',
};
