<?php
/**
 * Static prerender early-serve installer.
 *
 * @package Blockstudio
 */

namespace Blockstudio;

/**
 * Installs a product-neutral advanced-cache.php drop-in for prerender hits.
 *
 * The generated drop-in reads a small per-site route map and streams safe
 * anonymous HTML before WordPress, plugins, or the active theme boot. Existing
 * foreign maps, drop-ins, and WP_CACHE declarations are never overwritten.
 *
 * @since 7.6.0
 */
final class Static_Prerender_Early_Serve {

	/**
	 * Generated drop-in format.
	 *
	 * @var int
	 */
	public const DROPIN_VERSION = 1;

	/**
	 * Ownership marker for the generated map.
	 *
	 * @var string
	 */
	private const MAP_MARKER = 'Generated by Blockstudio. Static prerender early-serve map; do not edit.';

	/**
	 * Ownership marker for the generated drop-in.
	 *
	 * @var string
	 */
	private const DROPIN_MARKER = 'Blockstudio static prerender early serve';

	/**
	 * Exact wp-config.php line owned by this class.
	 *
	 * @var string
	 */
	private const WP_CACHE_LINE = "define( 'WP_CACHE', true ); // Blockstudio static prerender early serve.";

	/**
	 * Test-only content directory override.
	 *
	 * @var string|null
	 */
	private static ?string $content_dir_override = null;

	/**
	 * Test-only WordPress configuration path override.
	 *
	 * @var string|null
	 */
	private static ?string $config_path_override = null;

	/**
	 * Synchronize the current site's map entry and shared drop-in.
	 *
	 * While the feature is disabled the lock is taken only when this class owns
	 * installed state, so a disabled site creates and reads no files at all.
	 *
	 * @return void
	 */
	public static function maybe_sync(): void {
		$content_dir = self::content_dir();
		if ( null === $content_dir || ! is_dir( $content_dir ) ) {
			return;
		}

		if (
			! Runtime_Settings::current()->enabled( 'staticPrerender/enabled' ) ||
			! Runtime_Settings::current()->enabled( 'staticPrerender/earlyServe' )
		) {
			if (
				! self::file_contains_marker( self::map_path(), self::MAP_MARKER ) &&
				! self::file_contains_marker( self::dropin_path(), self::DROPIN_MARKER )
			) {
				return;
			}

			self::with_exclusive_lock(
				self::map_path() . '.lock',
				static function (): bool {
					self::remove_current_site_locked();

					return true;
				}
			);

			return;
		}

		self::with_exclusive_lock(
			self::map_path() . '.lock',
			static function (): bool {
				$entry = self::current_entry();
				if ( null !== $entry && self::sync_map( $entry ) ) {
					self::ensure_dropin();
				}

				return true;
			}
		);
	}

	/**
	 * Return current host/home identity for deployment tooling.
	 *
	 * @return array{host:string,home_path:string,key:string}|null Site identity.
	 */
	public static function current_site_identity(): ?array {
		return self::current_site();
	}

	/**
	 * Return installed owned map entries.
	 *
	 * @return array<string,array<string,mixed>> Entries.
	 */
	public static function installed_map_entries(): array {
		return self::owned_map_entries() ?? array();
	}

	/**
	 * Remove the current site's owned entry and shared artifacts when unused.
	 *
	 * Other multisite entries and every foreign map, drop-in, or WP_CACHE
	 * declaration remain untouched.
	 *
	 * @return void
	 */
	public static function remove_current_site(): void {
		$content_dir = self::content_dir();
		if ( null === $content_dir || ! is_dir( $content_dir ) ) {
			return;
		}

		self::with_exclusive_lock(
			self::map_path() . '.lock',
			static function (): bool {
				self::remove_current_site_locked();

				return true;
			}
		);
	}

	/**
	 * Activate a complete dependency-graph artifact atomically.
	 *
	 * Every route is validated before the map rename makes it visible. Existing
	 * HTML is retained until after the new graph becomes active. Configuration
	 * stays authoritative: an artifact is never installed unless both
	 * `staticPrerender/enabled` and `staticPrerender/earlyServe` are true.
	 *
	 * @param array<string,mixed> $entry     Artifact entry.
	 * @param string              $cache_dir Directory containing route HTML.
	 *
	 * @return bool Whether the artifact was installed.
	 */
	public static function install_artifact_entry( array $entry, string $cache_dir ): bool {
		if (
			! Runtime_Settings::current()->enabled( 'staticPrerender/enabled' ) ||
			! Runtime_Settings::current()->enabled( 'staticPrerender/earlyServe' )
		) {
			return false;
		}

		$cache_dir = rtrim( wp_normalize_path( $cache_dir ), '/' );

		if ( '' === $cache_dir || ! is_dir( $cache_dir ) ) {
			return false;
		}

		return self::with_exclusive_lock(
			$cache_dir . '/.build.lock',
			static fn(): bool => self::with_exclusive_lock(
				self::map_path() . '.lock',
				static fn(): bool => self::install_artifact_entry_locked( $entry, $cache_dir )
			)
		);
	}

	/**
	 * Resolve the generated map path.
	 *
	 * @return string Path.
	 */
	public static function map_path(): string {
		return (string) self::content_dir() . '/blockstudio-static-prerender-map.php';
	}

	/**
	 * Resolve the WordPress advanced-cache drop-in path.
	 *
	 * @return string Path.
	 */
	public static function dropin_path(): string {
		return (string) self::content_dir() . '/advanced-cache.php';
	}

	/**
	 * Resolve WordPress content storage.
	 *
	 * @return string|null Directory.
	 */
	public static function content_dir(): ?string {
		if ( null !== self::$content_dir_override ) {
			return self::$content_dir_override;
		}

		return defined( 'WP_CONTENT_DIR' )
			? rtrim( wp_normalize_path( (string) WP_CONTENT_DIR ), '/' )
			: null;
	}

	/**
	 * Override the content directory in isolated tests.
	 *
	 * @param string|null $directory Directory or null to reset.
	 *
	 * @return void
	 */
	public static function override_content_dir_for_testing( ?string $directory ): void {
		self::$content_dir_override = null === $directory
			? null
			: rtrim( wp_normalize_path( $directory ), '/' );
	}

	/**
	 * Override the WordPress configuration path in isolated tests.
	 *
	 * @param string|null $path Path or null to reset.
	 *
	 * @return void
	 */
	public static function override_config_path_for_testing( ?string $path ): void {
		self::$config_path_override = null === $path
			? null
			: wp_normalize_path( $path );
	}

	/**
	 * Return the standalone generated drop-in source.
	 *
	 * @return string PHP source.
	 */
	public static function dropin_source(): string {
		$marker  = self::DROPIN_MARKER;
		$version = self::DROPIN_VERSION;

		return <<<PHP
<?php
// {$marker} v{$version} - generated by Blockstudio; do not edit.
// Streams anonymous-safe prerendered HTML before WordPress loads.

if ( 'GET' === strtoupper( (string) ( \$_SERVER['REQUEST_METHOD'] ?? 'GET' ) ) && ! ( defined( 'WP_CLI' ) && WP_CLI ) && 'cli' !== PHP_SAPI ) {
	blockstudio_early_serve_static_prerender();
}

function blockstudio_early_serve_static_prerender(): void {
	if ( '1' === (string) ( \$_SERVER['HTTP_X_BLOCKSTUDIO_STATIC_PRERENDER_WARM'] ?? '' ) ) {
		return;
	}
	foreach ( array( 'HTTP_X_BLOCKSTUDIO_PREVIEW', 'HTTP_X_BLOCKSTUDIO_CANVAS', 'HTTP_X_WP_NONCE' ) as \$header ) {
		if ( '' !== trim( (string) ( \$_SERVER[ \$header ] ?? '' ) ) ) {
			return;
		}
	}

	\$uri = (string) ( \$_SERVER['REQUEST_URI'] ?? '/' );
	if ( '' === \$uri || str_contains( \$uri, '?' ) ) {
		return;
	}

	\$path = strtolower( (string) ( parse_url( \$uri, PHP_URL_PATH ) ?: '/' ) );
	foreach ( array( '/wp-admin', '/wp-json', '/wp-login.php', '/xmlrpc.php' ) as \$prefix ) {
		if ( str_starts_with( \$path . '/', \$prefix . '/' ) ) {
			return;
		}
	}
	if ( str_contains( \$path, '/feed/' ) || '/feed' === substr( rtrim( \$path, '/' ), -5 ) || str_contains( \$path, '/search/' ) || str_contains( \$path, '/preview/' ) ) {
		return;
	}

	\$map_file = __DIR__ . '/blockstudio-static-prerender-map.php';
	if ( ! is_file( \$map_file ) ) {
		return;
	}

	\$map = include \$map_file;
	if ( ! is_array( \$map ) || empty( \$map['entries'] ) || ! is_array( \$map['entries'] ) ) {
		return;
	}

	\$host = strtolower( (string) ( \$_SERVER['HTTP_HOST'] ?? 'localhost' ) );
	\$host_without_port = parse_url( 'http://' . \$host, PHP_URL_HOST );
	\$host_without_port = is_string( \$host_without_port ) && '' !== \$host_without_port ? strtolower( \$host_without_port ) : \$host;
	\$entry = null;
	foreach ( \$map['entries'] as \$candidate ) {
		\$candidate_host = (string) ( \$candidate['host'] ?? '' );
		\$home_path = (string) ( \$candidate['home_path'] ?? '//' );
		if ( ( \$candidate_host === \$host || \$candidate_host === \$host_without_port ) && str_starts_with( \$path . '/', \$home_path ) ) {
			\$entry = \$candidate;
			break;
		}
	}
	if ( null === \$entry ) {
		return;
	}

	foreach ( (array) ( \$entry['dynamic'] ?? array() ) as \$dynamic_prefix ) {
		\$dynamic_prefix = rtrim( strtolower( (string) \$dynamic_prefix ), '/' );
		if ( '' !== \$dynamic_prefix && str_starts_with( \$path . '/', \$dynamic_prefix . '/' ) ) {
			return;
		}
	}

	\$has_user_cookie = false;
	foreach ( array_keys( \$_COOKIE ?? array() ) as \$cookie_name ) {
		\$cookie_name = strtolower( (string) \$cookie_name );
		if ( str_starts_with( \$cookie_name, 'wordpress_logged_in_' ) || str_starts_with( \$cookie_name, 'wp-postpass_' ) || str_starts_with( \$cookie_name, 'comment_author_email_' ) ) {
			\$has_user_cookie = true;
			break;
		}
	}
	if ( \$has_user_cookie && empty( \$entry['serve_logged_in'] ) ) {
		return;
	}

	\$route_path = strtolower( '/' . ltrim( (string) ( parse_url( \$uri, PHP_URL_PATH ) ?: '/' ), '/' ) );
	\$route_path = (string) ( preg_replace( '#/+#', '/', \$route_path ) ?: '/' );
	if ( 'graph' === ( \$entry['mode'] ?? null ) ) {
		\$routes = is_array( \$entry['routes'] ?? null ) ? \$entry['routes'] : array();
		\$key = isset( \$routes[ \$route_path ] ) && is_string( \$routes[ \$route_path ] ) ? \$routes[ \$route_path ] : '';
		if ( ! preg_match( '/^[a-f0-9]{64}$/', \$key ) ) {
			return;
		}
	} else {
		\$key = hash( 'sha256', \$host . '|' . \$route_path . '|' . (string) ( \$entry['signature'] ?? '' ) );
	}

	\$directory = rtrim( (string) ( \$entry['dir'] ?? '' ), '/' );
	if ( '' === \$directory ) {
		return;
	}
	\$file = \$directory . '/' . \$key . '.html';
	if ( ! is_file( \$file ) || ! is_readable( \$file ) ) {
		return;
	}

	\$ttl = (int) ( \$entry['ttl'] ?? 86400 );
	if ( \$ttl > 0 && (int) filemtime( \$file ) < time() - \$ttl ) {
		return;
	}

	\$contents = file_get_contents( \$file );
	if ( false === \$contents || '' === \$contents ) {
		return;
	}

	if ( ! headers_sent() ) {
		header( 'Content-Type: text/html; charset=UTF-8' );
		header( 'X-Blockstudio-Static-Prerender: HIT-EARLY' );
	}

	echo \$contents;
	exit;
}

PHP;
	}

	/**
	 * Build the current site's map entry.
	 *
	 * @return array<string,mixed>|null Entry.
	 */
	private static function current_entry(): ?array {
		$site = self::current_site();
		if ( null === $site ) {
			return null;
		}

		if ( 'graph' === Runtime_Settings::current()->value( 'staticPrerender/invalidate', 'signature' ) ) {
			$entries = self::owned_map_entries();
			$active  = is_array( $entries ) && is_array( $entries[ $site['key'] ] ?? null )
				? $entries[ $site['key'] ]
				: null;

			return is_array( $active ) && 'graph' === ( $active['mode'] ?? null )
				? $active
				: null;
		}

		$dynamic = self::dynamic_paths( $site['home_path'] );

		return array(
			'host'            => $site['host'],
			'home_path'       => $site['home_path'],
			'site_id'         => function_exists( 'get_current_blog_id' ) ? (int) get_current_blog_id() : 0,
			'dir'             => Static_Prerender_Runtime::cache_root_path(),
			'mode'            => 'signature',
			'signature'       => Static_Prerender_Identity::current(),
			'ttl'             => (int) Runtime_Settings::current()->value( 'staticPrerender/ttl', 86400 ),
			'serve_logged_in' => Runtime_Settings::current()->enabled( 'staticPrerender/serveLoggedIn' ),
			'dynamic'         => $dynamic,
		);
	}

	/**
	 * Resolve the current host and WordPress home path.
	 *
	 * @return array{host:string,home_path:string,key:string}|null Site.
	 */
	private static function current_site(): ?array {
		if ( ! function_exists( 'home_url' ) ) {
			return null;
		}

		$home  = (string) home_url( '/' );
		$parts = wp_parse_url( $home );
		if ( ! is_array( $parts ) || ! is_string( $parts['host'] ?? null ) || '' === $parts['host'] ) {
			return null;
		}

		$host = strtolower( $parts['host'] );
		if ( is_int( $parts['port'] ?? null ) ) {
			$host .= ':' . $parts['port'];
		}

		$home_path = self::normalize_home_path( (string) ( $parts['path'] ?? '/' ) );

		return array(
			'host'      => $host,
			'home_path' => $home_path,
			'key'       => $host . '|' . $home_path,
		);
	}

	/**
	 * Synchronize one ordinary signature-mode entry.
	 *
	 * @param array<string,mixed> $entry Entry.
	 *
	 * @return bool Whether synchronized.
	 */
	private static function sync_map( array $entry ): bool {
		$entries = self::owned_map_entries();
		if ( null === $entries ) {
			return false;
		}

		$key = (string) $entry['host'] . '|' . (string) $entry['home_path'];
		if ( ( $entries[ $key ] ?? null ) === $entry ) {
			return true;
		}

		$entries[ $key ] = $entry;

		return self::write_map( $entries );
	}

	/**
	 * Install a graph entry while both locks are held.
	 *
	 * @param array<string,mixed> $entry     Entry.
	 * @param string              $cache_dir Cache directory.
	 *
	 * @return bool Whether installed.
	 */
	private static function install_artifact_entry_locked( array $entry, string $cache_dir ): bool {
		$host      = isset( $entry['host'] ) && is_scalar( $entry['host'] )
			? strtolower( trim( (string) $entry['host'] ) )
			: '';
		$home_path = self::normalize_home_path(
			isset( $entry['home_path'] ) && is_scalar( $entry['home_path'] )
				? (string) $entry['home_path']
				: '/'
		);
		$routes    = array();

		if ( '' === $host || str_contains( $host, '/' ) || str_contains( $host, "\0" ) ) {
			return false;
		}

		foreach ( is_array( $entry['routes'] ?? null ) ? $entry['routes'] : array() as $path => $key ) {
			if ( ! is_string( $path ) || ! is_string( $key ) || 1 !== preg_match( '/^[a-f0-9]{64}$/', $key ) ) {
				return false;
			}

			$path = strtolower( '/' . ltrim( self::url_path( $path ), '/' ) );
			$path = preg_replace( '#/+#', '/', $path );
			$path = is_string( $path ) && '' !== $path ? $path : '/';
			if ( ! str_starts_with( $path . '/', $home_path ) ) {
				return false;
			}
			if ( ! is_file( $cache_dir . '/' . $key . '.html' ) || ! is_readable( $cache_dir . '/' . $key . '.html' ) ) {
				return false;
			}

			$routes[ $path ] = $key;
		}

		ksort( $routes, SORT_STRING );
		if ( array() === $routes ) {
			return false;
		}

		$build_id = isset( $entry['build_id'] ) && is_string( $entry['build_id'] )
			? strtolower( trim( $entry['build_id'] ) )
			: '';
		if ( 1 !== preg_match( '/^[a-f0-9]{32}$/', $build_id ) ) {
			$build_id = hash(
				'xxh128',
				(string) wp_json_encode( array( $entry['signature'] ?? '', $routes ) )
			);
		}

		$normalized = array(
			'host'            => $host,
			'home_path'       => $home_path,
			'site_id'         => isset( $entry['site_id'] ) && is_numeric( $entry['site_id'] )
				? (int) $entry['site_id']
				: 0,
			'dir'             => $cache_dir,
			'mode'            => 'graph',
			'build_id'        => $build_id,
			'signature'       => isset( $entry['signature'] ) && is_scalar( $entry['signature'] )
				? (string) $entry['signature']
				: '',
			'ttl'             => isset( $entry['ttl'] ) && is_numeric( $entry['ttl'] )
				? max( 0, (int) $entry['ttl'] )
				: 86400,
			'serve_logged_in' => ! empty( $entry['serve_logged_in'] ),
			'dynamic'         => self::normalize_dynamic_paths(
				is_array( $entry['dynamic'] ?? null ) ? $entry['dynamic'] : array(),
				$home_path
			),
			'routes'          => $routes,
		);
		$entries    = self::owned_map_entries();

		if ( null === $entries ) {
			return false;
		}

		$entries[ $host . '|' . $home_path ] = $normalized;
		if (
			! self::ensure_dropin() ||
			! self::write_map( $entries ) ||
			! Static_Prerender_Identity::activate( $build_id )
		) {
			return false;
		}

		self::garbage_collect_after_swap( $entries, $cache_dir );

		return true;
	}

	/**
	 * Execute a callback under an exclusive filesystem lock.
	 *
	 * @param string          $path     Lock path.
	 * @param callable():bool $callback Callback.
	 *
	 * @return bool Callback result.
	 */
	private static function with_exclusive_lock( string $path, callable $callback ): bool {
		$directory = dirname( $path );
		if ( ! is_dir( $directory ) ) {
			wp_mkdir_p( $directory );
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fopen, WordPress.PHP.NoSilencedErrors.Discouraged -- flock requires a native stream and failure is handled.
		$handle = @fopen( $path, 'c+b' );
		if ( false === $handle ) {
			return false;
		}
		if ( ! flock( $handle, LOCK_EX ) ) { // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_flock -- Coordinates map cutovers.
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose -- Closes native lock handle.
			fclose( $handle );

			return false;
		}

		try {
			return $callback();
		} finally {
			flock( $handle, LOCK_UN ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_flock -- Releases map lock.
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_fclose -- Closes native lock handle.
			fclose( $handle );
		}
	}

	/**
	 * Remove the current site without disturbing other multisite entries.
	 *
	 * A foreign map owner is never cleaned up, because its entries cannot be
	 * attributed to this installation.
	 *
	 * @return void
	 */
	private static function remove_current_site_locked(): void {
		$entries = self::owned_map_entries();
		if ( null === $entries ) {
			return;
		}
		if ( array() === $entries ) {
			self::remove_owned_map();
			self::remove_shared_artifacts();

			return;
		}

		$site = self::current_site();
		if ( null === $site ) {
			return;
		}

		$site_id = function_exists( 'get_current_blog_id' ) ? (int) get_current_blog_id() : 0;
		$removed = false;

		foreach ( $entries as $key => $entry ) {
			$entry_site_id = is_numeric( $entry['site_id'] ?? null ) ? (int) $entry['site_id'] : -1;
			if ( $key === $site['key'] || $entry_site_id === $site_id ) {
				unset( $entries[ $key ] );
				$removed = true;
			}
		}

		if ( ! $removed ) {
			return;
		}

		if ( array() !== $entries ) {
			self::write_map( $entries );

			return;
		}

		self::remove_owned_map();
		self::remove_shared_artifacts();
	}

	/**
	 * Read owned entries, or null when a foreign file owns the path.
	 *
	 * @return array<string,array<string,mixed>>|null Entries.
	 */
	private static function owned_map_entries(): ?array {
		$map_path = self::map_path();
		if ( ! is_file( $map_path ) ) {
			return array();
		}
		if ( ! self::file_contains_marker( $map_path, self::MAP_MARKER ) ) {
			return null;
		}

		try {
			$existing = include $map_path;
		} catch ( \Throwable ) {
			return array();
		}

		if ( ! is_array( $existing ) || ! is_array( $existing['entries'] ?? null ) ) {
			return array();
		}

		$entries = array();
		foreach ( $existing['entries'] as $key => $entry ) {
			if ( is_string( $key ) && is_array( $entry ) ) {
				$entries[ $key ] = $entry;
			}
		}

		return $entries;
	}

	/**
	 * Publish the per-site map.
	 *
	 * @param array<string,array<string,mixed>> $entries Entries.
	 *
	 * @return bool Whether published.
	 */
	private static function write_map( array $entries ): bool {
		uasort(
			$entries,
			static fn( array $left, array $right ): int => strlen( self::entry_home_path( $right ) )
				<=> strlen( self::entry_home_path( $left ) )
		);

		$export = "<?php\n// " . self::MAP_MARKER . "\nreturn "
			. var_export( array( 'entries' => $entries ), true ) // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export -- Generates a data-only PHP map consumed before WordPress boots.
			. ";\n";

		return Single_Flight::publish( self::map_path(), $export );
	}

	/**
	 * Delete HTML not referenced by any graph in the same cache directory.
	 *
	 * @param array<string,array<string,mixed>> $entries   Entries.
	 * @param string                            $cache_dir Cache directory.
	 *
	 * @return void
	 */
	private static function garbage_collect_after_swap( array $entries, string $cache_dir ): void {
		$live   = array();
		$can_gc = true;

		foreach ( $entries as $candidate ) {
			$candidate_dir = isset( $candidate['dir'] ) && is_scalar( $candidate['dir'] )
				? rtrim( wp_normalize_path( (string) $candidate['dir'] ), '/' )
				: '';
			if ( $candidate_dir !== $cache_dir ) {
				continue;
			}
			if ( 'graph' !== ( $candidate['mode'] ?? null ) || ! is_array( $candidate['routes'] ?? null ) ) {
				$can_gc = false;
				break;
			}

			foreach ( $candidate['routes'] as $key ) {
				if ( is_string( $key ) ) {
					$live[ $key ] = true;
				}
			}
		}

		if ( ! $can_gc ) {
			return;
		}

		$files = glob( $cache_dir . '/*.html' );
		foreach ( is_array( $files ) ? $files : array() as $file ) {
			if ( ! isset( $live[ basename( $file, '.html' ) ] ) ) {
				wp_delete_file( $file );
			}
		}
	}

	/**
	 * Read an entry home path.
	 *
	 * @param array<string,mixed> $entry Entry.
	 *
	 * @return string Home path.
	 */
	private static function entry_home_path( array $entry ): string {
		return is_scalar( $entry['home_path'] ?? null ) ? (string) $entry['home_path'] : '';
	}

	/**
	 * Install or refresh the owned drop-in.
	 *
	 * @return bool Whether ready.
	 */
	private static function ensure_dropin(): bool {
		$dropin = self::dropin_path();

		if ( is_file( $dropin ) ) {
			// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reads only the ownership header.
			$head = (string) file_get_contents( $dropin, false, null, 0, 400 );
			if ( ! str_contains( $head, self::DROPIN_MARKER ) ) {
				return false;
			}
			if ( str_contains( $head, 'v' . self::DROPIN_VERSION . ' ' ) ) {
				self::ensure_wp_cache_constant();

				return true;
			}
		}

		if ( ! Single_Flight::publish( $dropin, self::dropin_source() ) ) {
			return false;
		}

		self::ensure_wp_cache_constant();

		return true;
	}

	/**
	 * Add the owned WP_CACHE declaration when no declaration exists.
	 *
	 * @return void
	 */
	private static function ensure_wp_cache_constant(): void {
		if ( defined( 'WP_CACHE' ) && WP_CACHE ) {
			return;
		}

		$config = self::config_path();
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_is_writable -- WordPress has no safe wp-config.php filesystem abstraction at this bootstrap boundary.
		if ( null === $config || ! is_writable( $config ) ) {
			return;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reads wp-config.php before an owned atomic patch.
		$contents = (string) file_get_contents( $config );
		if ( str_contains( $contents, 'WP_CACHE' ) ) {
			return;
		}

		$patched = preg_replace( '/^<\?php/', "<?php\n" . self::WP_CACHE_LINE, $contents, 1 );
		if ( is_string( $patched ) && $patched !== $contents ) {
			Single_Flight::publish( $config, $patched );
		}
	}

	/**
	 * Remove the owned shared drop-in and constant.
	 *
	 * @return void
	 */
	private static function remove_shared_artifacts(): void {
		$dropin = self::dropin_path();
		if ( is_file( $dropin ) && self::file_contains_marker( $dropin, self::DROPIN_MARKER ) ) {
			wp_delete_file( $dropin );
		}

		self::remove_owned_wp_cache_constant();
	}

	/**
	 * Remove the owned empty map.
	 *
	 * @return void
	 */
	private static function remove_owned_map(): void {
		$map = self::map_path();
		if ( is_file( $map ) && self::file_contains_marker( $map, self::MAP_MARKER ) ) {
			wp_delete_file( $map );
		}
	}

	/**
	 * Remove only Blockstudio's exact WP_CACHE declaration.
	 *
	 * @return void
	 */
	private static function remove_owned_wp_cache_constant(): void {
		$config = self::config_path();
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_is_writable -- WordPress has no safe wp-config.php filesystem abstraction at this bootstrap boundary.
		if ( null === $config || ! is_writable( $config ) ) {
			return;
		}

		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Reads wp-config.php before an owned atomic patch.
		$contents = (string) file_get_contents( $config );
		$patched  = preg_replace(
			'/^[\t ]*' . preg_quote( self::WP_CACHE_LINE, '/' ) . '[\t ]*(?:\R|$)/m',
			'',
			$contents,
			1
		);

		if ( is_string( $patched ) && $patched !== $contents ) {
			Single_Flight::publish( $config, $patched );
		}
	}

	/**
	 * Locate WordPress configuration without inventing a new host contract.
	 *
	 * @return string|null Path.
	 */
	private static function config_path(): ?string {
		if ( null !== self::$config_path_override ) {
			return self::$config_path_override;
		}

		if ( ! defined( 'ABSPATH' ) ) {
			return null;
		}

		foreach ( array( ABSPATH . 'wp-config.php', dirname( rtrim( ABSPATH, '/\\' ) ) . '/wp-config.php' ) as $path ) {
			if ( is_file( $path ) ) {
				return wp_normalize_path( $path );
			}
		}

		return null;
	}

	/**
	 * Test file ownership from a short header read.
	 *
	 * @param string $path   Path.
	 * @param string $marker Marker.
	 *
	 * @return bool Whether owned.
	 */
	private static function file_contains_marker( string $path, string $marker ): bool {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents, WordPress.PHP.NoSilencedErrors.Discouraged -- Reads only an ownership header and treats failures as foreign/absent.
		$head = @file_get_contents( $path, false, null, 0, 400 );

		return is_string( $head ) && str_contains( $head, $marker );
	}

	/**
	 * Resolve configured dynamic paths beneath the current home path.
	 *
	 * @param string $home_path Home path.
	 *
	 * @return string[] Paths.
	 */
	private static function dynamic_paths( string $home_path ): array {
		return self::normalize_dynamic_paths(
			(array) Runtime_Settings::current()->value( 'staticPrerender/dynamicPaths', array() ),
			$home_path
		);
	}

	/**
	 * Normalize dynamic path prefixes and contain them within one site.
	 *
	 * @param array<mixed> $paths     Paths.
	 * @param string       $home_path Home path.
	 *
	 * @return string[] Paths.
	 */
	private static function normalize_dynamic_paths( array $paths, string $home_path ): array {
		$normalized = array();

		foreach ( $paths as $path ) {
			if ( ! is_string( $path ) || '' === trim( $path ) ) {
				continue;
			}

			$path = strtolower( '/' . ltrim( $path, '/' ) );
			if ( ! str_starts_with( $path . '/', $home_path ) ) {
				$path = strtolower( $home_path . ltrim( $path, '/' ) );
			}
			$normalized[ rtrim( $path, '/' ) ] = true;
		}

		$paths = array_keys( $normalized );
		sort( $paths, SORT_STRING );

		return $paths;
	}

	/**
	 * Normalize a site home path.
	 *
	 * @param string $path Home path.
	 *
	 * @return string Path.
	 */
	private static function normalize_home_path( string $path ): string {
		$path = '/' . trim( $path, '/' );

		return strtolower( '/' === $path ? '/' : $path . '/' );
	}

	/**
	 * Parse a URL/path and return a safe path.
	 *
	 * @param string $value URL or path.
	 *
	 * @return string Path.
	 */
	private static function url_path( string $value ): string {
		$path = wp_parse_url( $value, PHP_URL_PATH );

		return is_string( $path ) && '' !== $path ? $path : '/';
	}
}
