import { makeActionCreator } from '@/utils/makeActionCreator';

export const actions = {
  closeEditor: makeActionCreator('CLOSE_EDITOR', 'isEditor'),
  formatCode: makeActionCreator('FORMAT_CODE', 'formatCode'),
  openEditor: makeActionCreator(
    'OPEN_EDITOR',
    'block',
    'errors',
    'filesChanged',
    'isEditor',
    'isStatic',
    'path',
  ),
  setBlock: makeActionCreator('SET_BLOCK', 'block', 'path'),
  setBlockData: makeActionCreator('SET_BLOCK_DATA', 'block'),
  setBlockResets: makeActionCreator('SET_BLOCK_RESETS', 'blockResets'),
  setBlocks: makeActionCreator('SET_BLOCKS', 'blocks'),
  setBlocksNative: makeActionCreator('SET_BLOCKS_NATIVE', 'blocksNative'),
  setContextMenu: makeActionCreator('SET_CONTEXT_MENU', 'contextMenu'),
  setConsole: makeActionCreator('SET_CONSOLE', 'console'),
  setEditor: makeActionCreator('SET_EDITOR', 'editor'),
  setEditorMounted: makeActionCreator('SET_EDITOR_MOUNTED', 'editorMounted'),
  setErrors: makeActionCreator('SET_ERRORS', 'errors'),
  setFiles: makeActionCreator('SET_FILES', 'files'),
  setFilesChanged: makeActionCreator('SET_FILES_CHANGED', 'filesChanged'),
  setFolders: makeActionCreator('SET_FOLDERS', 'filesFolders'),
  setIsImport: makeActionCreator('SET_IS_IMPORT', 'isImport'),
  setIsGutenberg: makeActionCreator('SET_IS_GUTENBERG', 'isGutenberg'),
  setIsModalSave: makeActionCreator('SET_IS_MODAL_SAVE', 'isModalSave'),
  setIsStatic: makeActionCreator('SET_IS_STATIC', 'isStatic'),
  setMove: makeActionCreator('SET_MOVE', 'move'),
  setNewBlock: makeActionCreator('SET_NEW_BLOCK', 'newBlock'),
  setNewFile: makeActionCreator('SET_NEW_FILE', 'newFile'),
  setNewFolder: makeActionCreator('SET_NEW_FOLDER', 'newFolder'),
  setNewInstance: makeActionCreator('SET_NEW_INSTANCE', 'newInstance'),
  setNextBlock: makeActionCreator('SET_NEXT_BLOCK', 'nextBlock'),
  setOptions: makeActionCreator('SET_OPTIONS', 'options'),
  setRename: makeActionCreator('SET_RENAME', 'rename'),
  setPath: makeActionCreator('SET_PATH', 'path'),
  setPreview: makeActionCreator('SET_PREVIEW', 'preview'),
  setSearchedBlocks: makeActionCreator('SET_SEARCHED_BLOCKS', 'searchedBlocks'),
  setSettings: makeActionCreator('SET_SETTINGS', 'settings'),
  setTree: makeActionCreator('SET_TREE', 'tree'),
  setTreeOpen: makeActionCreator('SET_TREE_OPEN', 'treeOpen'),
};
